spring:
  application:
    name: spring-jwt-auth-example
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

jwt:
  secret: 5779f9d216255512fefeb3308a1ad627
  refresh-ttl: 604800
