spring:
  application:
    name: spring-jwt-auth-example
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

jwt:
  refresh-ttl: 604800
