create table role (
    id integer generated by default as identity primary key,
    role_name varchar(50) not null unique
);

create table person (
    id integer generated by default as identity primary key,
    login varchar(50) not null unique,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    password_hash varchar(255) not null,
    created timestamp not null,
    last_login timestamp,
    role_id integer not null references role(id)
);

insert into role(role_name) values ('user'), ('admin');

insert into person (login, first_name, last_name, password_hash, created, last_login, role_id)
values (
    'user',
    'John',
    'Doe',
    '$2b$12$wR/8g2e5TYKYvbWe1YxAYePzkMF3/kT5w0oj3a1OaNLOrTgfBh2r.',
    current_timestamp,
    current_timestamp,
    (select id from role where role_name = 'admin')
);
